### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by anuj9196** [ushelp/EasyQRCodeJS-NodeJS#1]
I'm trying to use it in **Angular 8**.

I added following in the **component.ts**  file
```
const qr = require('easyqrcodejs-nodejs');
```

But it is giving error
```
ERROR in ./node_modules/easyqrcodejs-nodejs/index.min.js
Module not found: Error: Can't resolve 'fs' in '/home/scanova/code/scanova/qcg-frontend/node_modules/easyqrcodejs-nodejs'
```

**Comment by ushelp** [comment]
@anuj9196 

Hey, For Angular 8, May be you means [EasyQRCodeJS](https://github.com/ushelp/EasyQRCodeJS#angular-support), not **EasyQRCodeJS-NodeJS**?
