### ISSUE TITLE
Not working in ExpressJS Server

### ISSUE THREAD

**Issue by ebitogu** [ushelp/EasyQRCodeJS-NodeJS#17]
Hello, thanks for the work put into this awesome library.

However, I just wanted to confirm if this truly works on an expressjs app. Because, I tried your samples in my express app and the generated code isn't readable by any qr code scanner.

Here is what I tried:
```

 let options = {
            text: "sample_data",
            width: 320,
            height: 320,
            correctLevel: QRCode.CorrectLevel.H, // L, M, Q, H
            dotScale: 0.4,
            colorDark: "#473C8B",
            colorLight: "#FFFACD",
            quietZone: 15,
            quietZoneColor: '#00CED1',
            PI: '#BF3030',
            PO: '#269926',
            PI_TL: '#b7d28d',
            PO_TL: '#aa5b71',
            AI: '#009ACD',
            AO: '#B03060',
            timing_H: '#ff6600',
            timing_V: '#cc0033',
            logo: "public/icons/logo.png",
            logoBackgroundColor: '#FFF8DC',
            logoBackgroundTransparent: false
        };
        let qrcode = new QRCode(options);
        qrcode.saveImage({
            path: 'code.png'
        });
        return "";
```

The QR code was generated fine, but I can't seem to read it with any qr code scanner. It's really weird.

Help would be really appreciated.

**Comment by ushelp** [comment]
After I tested your code, the color of quietZone may affect the scanne of some apps. 

 ### OK for iPhoneCamera/QRefine APP/WeChat APP...
![code](https://user-images.githubusercontent.com/4082017/120671910-6a3dc800-c4c4-11eb-9e02-bb7cd60674ce.png)

![code](https://user-images.githubusercontent.com/4082017/120672493-ef28e180-c4c4-11eb-9eb0-9aace0e19ad4.png)

 ### OK for iPhone Camera/WeChat APP, but QRefine APP doesn't work
![code](https://user-images.githubusercontent.com/4082017/120671989-7aee3e00-c4c4-11eb-81d6-a06ea7f1dd9e.png)


Could you tell me the APP or device information you use?

**Comment by ebitogu** [comment]
After much frustration I removed all that many configs and simply used the following code and it works now:

 ```
static async generateQRCode(data) {
        let options = {
            text: data,
            width: 450,
            height: 450,
            logo: "public/icons/logo.png",
        };
        let qrcode = new QRCode(options);
        return qrcode.toDataURL();
    }
```

**Comment by ushelp** [comment]
Haha, the support of this scanner is too basic.
