### ISSUE TITLE
some problems with svg after saving

### ISSUE THREAD

**Issue by rprokopenko** [ushelp/EasyQRCodeJS-NodeJS#20]
Hi again,

I found some more problems after saving in svg format.

1. When we save in svg format and then open this svg, the qrcode is not clear, there are white gaps between the black squares. As a result, it is not possible to scan the qrcode. Example: 
![123](https://user-images.githubusercontent.com/64587009/126771541-fe0b40c6-ec46-43c4-86df-e0a2c9d93769.png)

2. If we open svg with chrome, then the logo is visible, but if we open svg through some editor or just load it somewhere, then the logo disappears. Example: 
![Screenshot_10](https://user-images.githubusercontent.com/64587009/126771858-22e81273-d9a9-4176-877f-7dfe842c11c5.png)

Thanks in advance for the help.

**Comment by ushelp** [comment]
1. About line between tiled SVG shapes, it's because of antialiasing at work between the shape and the background. 

2. We optimized the svg image size, so you may not be able to work on other editors.

**Comment by rprokopenko** [comment]
> 1. About line between tiled SVG shapes, it's because of antialiasing at work between the shape and the background.
> 2. We optimized the svg image size, so you may not be able to work on other editors.

1. Then the question is how can I fix these white line between tiled SVG shapes? Maybe there is some kind of setting in the configuration file?

2. Probably you didn’t quite understand me when I saved the qrcode with the logo in svg format and tried to open this file somewhere, for example Photoshop or Figma, then the logo disappears and the qrcode itself remains, but if you open it with the browser, the logo is visible

**Comment by ushelp** [comment]
Q1. Sorry, we currently don’t have a solution can to fix the white line issues. if you want to avoid this problem please use CANVAS as the drawer.

Q2. We link to image use src attribute, please check the svg code, can make sure your editor can access the logo image.

**Comment by ushelp** [comment]
Closed due to no reply for a long time.
