### ISSUE TITLE
.toDataUrl() returns "Server Responded with 403"

### ISSUE THREAD

**Issue by sivunq** [ushelp/EasyQRCodeJS-NodeJS#26]
```
let options = {
			text: "something",
			width: 425,
			height: 425,
			colorDark: "#2eb567",
			colorLight: "#FFFFFF",
			correctLevel: QRCode.CorrectLevel.H,
			quality: 1,
			// ====== Quiet Zone
			quietZone: 10,
			quietZoneColor: "#FFFFFF",
			logo: logoUrl, //public logo url
			logoBackgroundColor: '#FFFFFF'
		};

		// New instance with options
		let qrcode = new QRCode(options);

		let base64QrData: any = '';
		try {
			await qrcode.toDataURL().then((data: any) => {
				base64QrData = data;
			});
		} catch (err: any) {
			console.log("Error while creating qr code", err);
		}
```

		
		
		I'm getting following error in console:
		Error while creating qr code "Server responded with 403"
		
		"    at /home/node/app/node_modules/simple-get/index.js:89:7",
		"    at /home/node/app/node_modules/canvas/lib/image.js:56:28",
		
	this is only happening in production, i'm not able to reproduce it

**Comment by sivunq** [comment]
@ushelp @imtheknown

**Comment by ushelp** [comment]
This error is a response from the server that you requested an external resource, I think it's `logoUrl` request error. 
Please check the logoUrl you can access.

**Comment by sivunq** [comment]
logoUrl is public, i am able to access it, that should not be an issue. i'm suspecting it's a security exception related to canvas

**Comment by ushelp** [comment]
You can get the error "Server responded with 403",  it means the URL request already sent, but the server responsed an error to client.

Some advice for you to check:
- Use another logoUrl to test
- Debug the canvas request, get the detail request information for logoUrl

**Comment by ushelp** [comment]
You can get the error "Server responded with 403",  it means the URL request already sent, but the server responsed an error to client.

Some advice for you to check:
- Use another logoUrl to test
- Debug the canvas request, get the detail request information for logoUrl
