### ISSUE TITLE
why sometime result is upcE ?

### ISSUE THREAD

**Issue by yogithesymbian** [ushelp/EasyQRCodeJS-NodeJS#28]
My QRCode result 
**QR 1 = BarcodeFormat.upcE**
QR 2 = BarcodeFormat.qrcode

can anyone tell me why sometime the result its not QRCode ?
what i save is **aes-256-cbc** **encryption text**
what i encrypt is uuid from `"uuidv4": "^6.2.12",` **date time** , and **3 other value** / secret (_short data_)

i know the result its different when i tried to scanning from `qr_code_scanner: ^0.5.2` flutter dependency https://pub.dev
so 1 of 10 qrcode have broken and cant to scanning because its not QRCode but its upcE.

when i scanning 1 of data:
```
[log] qrcode format : BarcodeFormat.upcE
[log] qrcode data : 13417680 // its not my encryption text (aes-256-cbc) // unexpected
```

other data its valid  9 of 10 data
```

[log] qrcode format : BarcodeFormat.qrcode
I/flutter (12777): qrcode data decryption : *******secret*****
[log] qrcode data : hILYH7JI/3Bch8f8x6NN6EyksfL/Kho8swerYC4c6gk08R01N+behSEO0F2IcucBhq9c5cll7ex23cGrqaKn3h3Iw5RsPeNhlVddSnKZ6WsLiHS62ZBWsx06oeRqlzXJBnYI0B8GWm20K7uvpTduGQ3vCVWgeSjXkvGV+G9QQLibKMIGD/mhHBWHx3jrlsGI
```

**Comment by ushelp** [comment]
can paste your QRCode image which scan incorrect?

**Comment by ushelp** [comment]
Close the issue due to no reponse for a long time.
