### ISSUE TITLE
SubTitle overlapse for long text

### ISSUE THREAD

**Issue by yogithesymbian** [ushelp/EasyQRCodeJS-NodeJS#33]
any solution ? i have subtitle that present name and date time with some description and big text.
but its overlapse on result.

<img width="438" alt="Screen Shot 2022-11-01 at 11 26 48 AM" src="https://user-images.githubusercontent.com/28316296/199152212-932c53c7-8aca-420b-8062-827ffd6068ce.png">

**Comment by yogithesymbian** [comment]
ah my bad i didnt see on readme.md

EasyQRCodeJS-Premium is a more powerful and comprehensive enterprise version. You can use Canvas to customize any element, such as eye frame shape, eyeball shape, QR code block shape, and more. Also supports excavation **(to prevent the QRcode overlap with the logo)**, random block mode.

**Comment by ushelp** [comment]
Hi, Yogi.

There is a workaround, you can increase the display width of the QR code by setting `quietZone`, for example: try to set the `quietZone: 30`.

But if you want to do more control, this will require EasyQRCodeJS-Premium..
