### ISSUE TITLE
generation qrcode with toDataUrl not working.

### ISSUE THREAD

**Issue by itsgratien** [ushelp/EasyQRCodeJS-NodeJS#42]
Hello,

I am getting this error everytime i am trying to generate qrcode using toDataUrl() method.

The following is the error I am getting: 
**Cannot set properties of undefined (setting 'width')","name":"TypeError","stack":"TypeError: Cannot set properties of undefined (setting 'width')\n    at Drawing.draw**

I would like your help. Thanks

**Comment by slb235** [comment]
seems like a problem only with the minified version in nodejs > 14, using the `.js` instead of `.min.js` solves this.

**Comment by ushelp** [comment]
Hi @slb235 and @itsgratien , thank you for your feedback. 

Please upgrade to version 4.5.1 to solve this issue.

**Comment by itsgratien** [comment]
Thank you @ushelp
